【Issue #130】パスワードリセット処理のEntityを作成
tech-quest/tq-twitter pull request #136
Opened 2022-07-13 06:26 UTC by clock-en

2022-07-13 07:00 UTC, clock-en commented on src/app/Domain/ValueObject/CertificationCode.php
> +}
`Certification` というValue Object があるのですが、インスタンス作成時に値オブジェクト内でコードをランダムで生成してしまうため、取り扱いがしにくかったので別で `CertificationCode` というオブジェクトを作成しました。
(postされた認証コードを値オブジェクトとして扱えないなど)

別のユースケースなどで `Certification` の値オブジェクトが使用されているため、そちらはまだ残してあります。

2022-07-14 08:27 UTC, KatsuyaTanaka95 approved these changes

2022-07-14 08:27 UTC, KatsuyaTanaka95 commented on src/app/UseCase/PasswordReset/CompletePasswordReset/Interactor.php
こちらもuseでUseCaseOutputを指定しなくても動きそうでしょうか？？
ご確認お願いいたします！^ ^

2022-07-14 08:27 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！！！
ご確認よろしくです！！^ ^

2022-07-15 11:14 UTC, clock-en commented on src/app/UseCase/PasswordReset/ConfirmUserCertification/Interactor.php
> +use App\Domain\Entity\PasswordResetCertification;
namespaceが同様のファイルになるので `Output` がなくても動作に問題はなさそうです。

以下、2通りの対応ができますがどうしましょう？
- 明示的に同じnamespaceでもuseを指定する
- Inputも不要であればuseの記述を削除する

2022-07-15 11:57 UTC, clock-en commented on src/app/Adapter/QueryService/PasswordResetCertificationQueryService.php
> +      new HashedCertificationCode($mapper['certification_code']),
こちら削除しました！

2022-07-15 12:38 UTC, clock-en commented
mainブランチの内容が変更されているようなので、マージを行いました。
また、mainブランチの内容を加味して以下調整を加えました。
- 今回作成した `PasswordResetCertificationQueryService` と `PasswordResetCertificationRepository` のinterfaceを作成
- 上記を使用するUseCaseを作成した interface に依存するように調整 (インスタンスの生成も呼び出し元で行うようにしています)
- Entity を生成する処理を Factory として別ファイル化

2022-07-19 11:57 UTC, KatsuyaTanaka95 commented on src/app/UseCase/PasswordReset/ConfirmUserCertification/Interactor.php
> +use App\Domain\Entity\PasswordResetCertification;
なるほど！そうなんですね！！
今回は、[明示的に同じnamespaceでもuseを指定する]ようにしましょうか！！^ ^

2022-07-20 01:41 UTC, KatsuyaTanaka95 approved these changes
LGTM^ ^
良い感じですね！！😊
mergeさせていただきます！！

2022-07-20 01:41 UTC, merged